# 🚀 Configuration Render pour MieteNow
# Ce fichier décrit tous les services nécessaires pour déployer l'application

services:
  # 🌐 Application Web Next.js
  - type: web
    name: mietenow-web
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    # Mode serveur uniquement (pas de prerendering)
    runtime: node
    envVars:
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: mietenow-web
          property: host

  # 🔄 Cron Job - Scraping quotidien
  - type: cron
    name: mietenow-scraper
    env: node
    region: frankfurt
    plan: starter
    schedule: "0 6,12,18 * * *"  # 3 fois par jour : 6h, 12h, 18h
    buildCommand: npm install
    startCommand: node scripts/cron-scraping-standalone.js
    envVars: []

  # 🧹 Cron Job - Nettoyage des anciennes annonces
  - type: cron
    name: mietenow-cleanup
    env: node
    region: frankfurt
    plan: starter
    schedule: "0 2 * * *"  # Tous les jours à 2h du matin
    buildCommand: npm install
    startCommand: node scripts/cron-cleanup-standalone.js
    envVars: []

  # 📧 Cron Job - Envoi des alertes
  - type: cron
    name: mietenow-alerts
    env: node
    region: frankfurt
    plan: starter
    schedule: "0 8,20 * * *"  # 2 fois par jour : 8h et 20h
    buildCommand: npm install
    startCommand: node scripts/cron-send-alerts.js
    envVars: []

  # 💰 Cron Job - Vérification des plans
  - type: cron
    name: mietenow-plans
    env: node
    region: frankfurt
    plan: starter
    schedule: "0 1 * * *"  # Tous les jours à 1h du matin
    buildCommand: npm install
    startCommand: node scripts/cron-check-plans.js
    envVars: []

# 🔧 Variables d'environnement partagées
# Ces variables doivent être configurées dans le dashboard Render
envVars:
  - key: MONGODB_URI
    description: "URI de connexion MongoDB Atlas"
  - key: JWT_SECRET
    description: "Clé secrète pour JWT"
  - key: NEXTAUTH_SECRET
    description: "Clé secrète pour NextAuth"
  - key: NEXTAUTH_URL
    description: "URL de l'application"
  - key: APIKEYSENDGRID
    description: "Clé API SendGrid pour les emails"
  - key: SENDGRID_FROM_EMAIL
    description: "Email d'expéditeur SendGrid"
  - key: NEXT_PUBLIC_STRIPE_API
    description: "Clé publique Stripe"
  - key: STRIPE_SECRET_KEY
    description: "Clé secrète Stripe"
  - key: STRIPE_WEBHOOK_SECRET
    description: "Secret webhook Stripe"
  - key: CLOUDINARY_URL
    description: "URL Cloudinary pour les images"
  - key: BRIGHT_DATA_USERNAME
    description: "Nom d'utilisateur Bright Data"
  - key: BRIGHT_DATA_PASSWORD
    description: "Mot de passe Bright Data"
  - key: BRIGHT_DATA_ENDPOINT
    description: "Endpoint Bright Data"

